[package]
name = "bevy_mod_cuicui"
version = "0.1.0"
edition = "2021"
exclude = ["assets"]

[features]
default = ["reflect"]
reflect = []

[dependencies]
bevy = { version = "0.9", default-features = false, features = ["bevy_render"] }

[dev-dependencies]
bevy-inspector-egui = "0.16"

[dev-dependencies.bevy]
features = ["png", "x11", "bevy_asset", "bevy_render"]
